#!/usr/bin/env python3
"""
Golden-frame generator for the MT6701 SSI decode in src/encoder/mt6701.c.

Produces tools/test/mt6701_golden.inc (checked in). The C decoder computes its CRC6
with a bit-serial LFSR; this generator computes the SAME CRC by textbook polynomial
long division -- a structurally DIFFERENT method, in a different language. Agreement
across many vectors makes a transcription bug (wrong shift/poly/bit-order) in either
side unlikely. The frame layout follows datasheet Rev.1.5 sec 6.8.2 (Figure 25):

  bits [23:10] D[13:0] 14-bit angle | bits [9:6] Mg[3:0] status | bits [5:0] CRC[5:0]
  CRC over the 18-bit (D[13:0]<<4 | Mg[3:0]), poly X^6+X+1, MSB-first.

Run:  python3 tools/test/gen_mt6701_golden.py > tools/test/mt6701_golden.inc

Notes:
- C28x has no uint8_t; mg/crc/flags are emitted as uint16_t, frame as uint32_t.
"""
import sys

POLY = 0b1000011  # X^6 + X + 1, degree 6


def crc6_polydiv(data18):
    """CRC6 by polynomial long division (independent of the C LFSR)."""
    reg = (data18 & 0x3FFFF) << 6           # append 6 zero bits
    for i in range(17 + 6, 5, -1):          # from the top data bit down to bit 6
        if (reg >> i) & 1:
            reg ^= POLY << (i - 6)
    return reg & 0x3F


def build_frame(angle, mg, crc_override=None):
    data18 = ((angle & 0x3FFF) << 4) | (mg & 0xF)
    crc = crc6_polydiv(data18) if crc_override is None else (crc_override & 0x3F)
    frame = ((angle & 0x3FFF) << 10) | ((mg & 0xF) << 6) | crc
    return frame


def decode_flags(mg):
    field_ok = (mg & 0x3) == 0
    track_ok = (mg & 0x8) == 0
    button = (mg & 0x4) != 0
    return field_ok, track_ok, button


# (angle, mg, crc_override) -- crc_override!=None forges a wrong CRC (negative vector)
VECTORS = [
    # valid frames, field/track normal, across the angle range
    (0x0000, 0x0, None),
    (0x0001, 0x0, None),
    (0x0002, 0x0, None),
    (0x1555, 0x0, None),
    (0x2AAA, 0x0, None),
    (0x1FFF, 0x0, None),
    (0x2000, 0x0, None),
    (0x3FFF, 0x0, None),
    (0x0ABC, 0x0, None),
    (0x1234, 0x0, None),
    # status-bit coverage (still CRC-valid)
    (0x1234, 0x1, None),   # field too strong  -> field_ok=0
    (0x1234, 0x2, None),   # field too weak    -> field_ok=0
    (0x1234, 0x4, None),   # push button       -> button=1, otherwise usable
    (0x1234, 0x8, None),   # loss of track     -> track_ok=0
    (0x3FFF, 0xF, None),   # all status bits set
    # negatives: correct layout but forged CRC -> crc_ok must be 0
    (0x1234, 0x0, 0x00),
    (0x2AAA, 0x0, 0x3F),
    (0x0ABC, 0x5, 0x2A),
]


def main():
    out = sys.stdout
    out.write("/* AUTO-GENERATED by tools/test/gen_mt6701_golden.py -- do not edit by hand. */\n")
    out.write("/* MT6701 SSI 24-bit frame golden vectors (CRC by independent poly long division). */\n\n")
    out.write("typedef struct {\n")
    out.write("    uint32_t frame;     /* raw 24-bit SSI frame */\n")
    out.write("    uint16_t angle;     /* expected D[13:0] */\n")
    out.write("    uint16_t mg;        /* expected Mg[3:0] */\n")
    out.write("    uint16_t crc;       /* CRC carried in the frame */\n")
    out.write("    uint16_t crc_ok;    /* expected CRC verdict */\n")
    out.write("    uint16_t field_ok;  /* Mg[1:0] normal */\n")
    out.write("    uint16_t track_ok;  /* Mg[3] no loss of track */\n")
    out.write("    uint16_t button;    /* Mg[2] push */\n")
    out.write("} mt6701_golden_t;\n\n")
    out.write("static const mt6701_golden_t MT6701_GOLDEN[] = {\n")
    for angle, mg, ovr in VECTORS:
        frame = build_frame(angle, mg, ovr)
        crc_in = frame & 0x3F
        crc_ok = 1 if ovr is None else (1 if (crc_in == crc6_polydiv(((angle & 0x3FFF) << 4) | (mg & 0xF))) else 0)
        field_ok, track_ok, button = decode_flags(mg)
        out.write("    { 0x%06lXUL, 0x%04X, 0x%X, 0x%02X, %d, %d, %d, %d },\n" % (
            frame, angle & 0x3FFF, mg & 0xF, crc_in,
            crc_ok, 1 if field_ok else 0, 1 if track_ok else 0, 1 if button else 0))
    out.write("};\n")
    out.write("#define MT6701_GOLDEN_N ((int)(sizeof(MT6701_GOLDEN)/sizeof(MT6701_GOLDEN[0])))\n")


if __name__ == "__main__":
    main()
